[2023-11-30T12:08:13.502+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-11-30T07:07:50.762429+00:00 [queued]>
[2023-11-30T12:08:13.519+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-11-30T07:07:50.762429+00:00 [queued]>
[2023-11-30T12:08:13.520+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-30T12:08:13.581+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-30 07:07:50.762429+00:00
[2023-11-30T12:08:13.595+0500] {standard_task_runner.py:57} INFO - Started process 4100 to run task
[2023-11-30T12:08:13.611+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-11-30T07:07:50.762429+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpbwstviyd']
[2023-11-30T12:08:13.615+0500] {standard_task_runner.py:85} INFO - Job 45: Subtask get_data
[2023-11-30T12:08:13.979+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-11-30T07:07:50.762429+00:00 [running]> on host mlops
[2023-11-30T12:08:14.985+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T07:07:50.762429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T07:07:50.762429+00:00'
[2023-11-30T12:08:14.989+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T12:08:14.992+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/get_data.py']
[2023-11-30T12:08:15.063+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T12:08:21.677+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T12:08:21.677+0500] {subprocess.py:93} INFO - 
[2023-11-30T12:08:21.678+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T12:08:21.678+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T12:08:21.678+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T12:08:21.678+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T12:08:21.679+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T12:08:21.679+0500] {subprocess.py:93} INFO - 2023/11/30 12:08:21 INFO mlflow.tracking.fluent: Experiment with name 'get_data' does not exist. Creating a new experiment.
[2023-11-30T12:09:30.772+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T12:09:30.925+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231130T070750, start_date=20231130T070813, end_date=20231130T070930
[2023-11-30T12:09:30.997+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T12:09:31.107+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
