[2023-11-30T16:47:53.537+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T11:45:09.352948+00:00 [queued]>
[2023-11-30T16:47:53.644+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T11:45:09.352948+00:00 [queued]>
[2023-11-30T16:47:53.653+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-30T16:47:53.849+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 11:45:09.352948+00:00
[2023-11-30T16:47:53.895+0500] {standard_task_runner.py:57} INFO - Started process 65713 to run task
[2023-11-30T16:47:53.966+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-11-30T11:45:09.352948+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpmptxcknx']
[2023-11-30T16:47:53.993+0500] {standard_task_runner.py:85} INFO - Job 61: Subtask train_model
[2023-11-30T16:47:55.296+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-11-30T11:45:09.352948+00:00 [running]> on host mlops
[2023-11-30T16:47:56.934+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T11:45:09.352948+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T11:45:09.352948+00:00'
[2023-11-30T16:47:56.941+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T16:47:56.975+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/train_model.py']
[2023-11-30T16:47:57.158+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T16:48:25.223+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T16:48:25.228+0500] {subprocess.py:93} INFO - 
[2023-11-30T16:48:25.242+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T16:48:25.243+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T16:48:25.247+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T16:48:25.248+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T16:48:25.249+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T16:48:25.273+0500] {subprocess.py:93} INFO - Registered model 'lr' already exists. Creating a new version of this model...
[2023-11-30T16:48:25.274+0500] {subprocess.py:93} INFO - 2023/11/30 16:48:25 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 2
[2023-11-30T16:48:25.867+0500] {subprocess.py:93} INFO - Created version '2' of model 'lr'.
[2023-11-30T16:48:25.868+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
[2023-11-30T16:48:25.871+0500] {subprocess.py:93} INFO -   return fit_method(estimator, *args, **kwargs)
[2023-11-30T16:48:27.220+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T16:48:27.688+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231130T114509, start_date=20231130T114753, end_date=20231130T114827
[2023-11-30T16:48:28.409+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T16:48:28.728+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
